import { Inter } from "next/font/google";
import Link from "next/link";
import './navbar.css'
import Navbar from "./components/navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <div className="footer-container">
          <Link href={'/'}>Footer</Link>
        </div>
        </body>
    </html>
  );
}